// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ConnectSSH(arg1:app.SSHConfig):Promise<void>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<app.QueryResult>;

export function LoadConfig():Promise<app.AppConfig>;

export function Pglogalyze(arg1:app.LogalyzeParams):Promise<string>;

export function RunSSHCommand(arg1:string):Promise<string>;

export function SaveConfig(arg1:app.AppConfig):Promise<void>;
