// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectSSH(arg1) {
  return window['go']['app']['App']['ConnectSSH'](arg1);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['app']['App']['ExecuteQuery'](arg1);
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function Pglogalyze(arg1) {
  return window['go']['app']['App']['Pglogalyze'](arg1);
}

export function RunSSHCommand(arg1) {
  return window['go']['app']['App']['RunSSHCommand'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}
