// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}
