// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<Array<Record<string, any>>>;
